---
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - actions
      - dependencies
    open-pull-requests-limit: 60

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - docker
      - dependencies
    open-pull-requests-limit: 60

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - pnpm
      - dependencies
    open-pull-requests-limit: 60

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - pip
      - dependencies
    open-pull-requests-limit: 60
