---
stages:
  - tests
  - dependencies
  - build
  - postbuild
  - deploy

include:
  - local: /ci/renovate.yml
  - local: /ci/docker.yml
  - local: /ci/tests.yml
  - local: /ci/pages.yml
  - local: /ci/netlify.yml
