---
blank_issues_enabled: false
contact_links:
  - name: EnvEdit on Gitlab
    url: https://gitlab.com/EnvEdit/EnvEdit
    about: All issues or code should be submitted to the Gitlab repository
  - name: EnvEdit Docs
    url: https://envedit.gitlab.io/EnvEdit/docs/
    about: Review the docs in case you missed something.
