---
name: MkDocs

"on":
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.4

      - uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.12.3
          cache: pipenv

      - name: Install dependencies
        run: |
          pip install pipenv==2023.12.1
          pipenv install --dev --system

      - uses: actions/cache@v4.0.2
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Build docs
        run: mkdocs build -d github-pages

      - name: Upload docs
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: "./github-pages"

  deploy:
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5.0.0

      - name: Publish docs
        id: deployment
        uses: actions/deploy-pages@v4.0.5
