---
name: MkDocs Pull Request

"on":
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.4

      - uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.12.3
          cache: pipenv

      - name: Install dependencies
        run: |
          pip install pipenv==2023.12.1
          pipenv install --dev --system

      - uses: actions/cache@v4.0.2
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Preparing build env
        run: python docs/scripts/prepareEnv.py

      - name: Build docs
        run: mkdocs build -d github-pages

      - name: Upload docs
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: "./github-pages"
          name: ${GITHUB_HEAD_REF}
