---
name: Build and Push Docker Image

"on":
  push:
    tags:
      - "**"
    branches:
      - master

jobs:
  build_push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4.1.1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0
        with:
          platforms: linux/arm64,linux/amd64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.2.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.0.0
        with:
          registry: "ghcr.io"
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker Image
        id: dockermeta
        uses: docker/metadata-action@v5.5.1
        with:
          images: |
            ghcr.io/${{ github.repository }}
            pinarruiz/envedit
          flavor: |
            latest=${{ startsWith(github.ref, 'refs/tags/') &&
            !contains(github.ref, 'alpha') &&
            !contains(github.ref, 'beta') }}
          tags: |
            type=ref,event=tag
            type=edge,branch=master

      - name: Build and Push to Container Registries
        uses: docker/build-push-action@v5.3.0
        with:
          platforms: linux/arm64,linux/amd64
          push: true
          cache-from: type=gha
          cache-to: type=gha
          tags: ${{ steps.dockermeta.outputs.tags }}
          labels: ${{ steps.dockermeta.outputs.labels }}
          provenance: false
          build-args: |
            NODE_VERSION=${{ steps.parseversion.outputs.node-version }}

      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v4.0.0
        with:
          repository: pinarruiz/envedit
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          short-description: ${{ github.event.repository.description }}

  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build_push
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4.1.1

      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          generateReleaseNotes: true
          prerelease: |
            ${{ contains(github.ref, 'alpha') ||
            contains(github.ref, 'beta') }}
          body: |
            ## Docker Images

            ```bash
            docker pull pinarruiz/envedit:${{ github.ref_name }}
            ```

            or

            ```bash
            docker pull ghcr.io/pinarruiz/envedit:${{ github.ref_name }}
            ```
